Import('env')

build  = env['CONFIG']['global']['build']['descriptive']
source = env['CONFIG']['global']['source']['descriptive']
data   = env['CONFIG']['global']['build']['prepare_data']

env.BuildStata(target  = ['#%s/summary.log'     % build,
                          '#%s/correlation.log' % build],
               source  = ['#%s/descriptive.do' % source,
                          '#%s/data.txt'      % data],
               log_ext = 'descriptive')

env.Install('#release', '#%s/' % build)
